set(_CATKIN_CURRENT_PACKAGE "webcam_description")
set(webcam_description_MAINTAINER "OriolOrra <oriolorraserra@gmail.com>")
set(webcam_description_DEPRECATED "")
set(webcam_description_VERSION "0.1.0")
set(webcam_description_BUILD_DEPENDS )
set(webcam_description_RUN_DEPENDS )
set(webcam_description_BUILDTOOL_DEPENDS "catkin")